Update interface.py
- Errors if arl/credentials are missing or empty on config
- Added priority for config ARL over stored one to easily swap between ARLs (without removing loginstorage.bin)
- Print if using email/password or arl to login the first time
- Fixes "AttributeError: 'DeezerAPI' object has no attribute 'language'" when trying to login with only an ARL on a fresh install